name: glds212-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - matplotlib
  - seaborn
  - scikit-bio
  - ipykernel
  - pip
  - pip:
      - shap
